name: Python application with Github Action

on: [push]

jobs:
   build:

   run-on: ubuntu-latest
   
steps:
   -uses: actions/checkout@v2
   -name: set up python 3.12
    uses: actions/setup-python@v1
    with:
      python-version:3.12
  - name: Install dependencies
      run: |
        make install
  -name: Lint with pylint
    run: |
      make lint
  -name : Test with pytest
    run: |
      make test
  -name : Format code
    run: |
      make format
  |
